pull_request_rules:

  - name: Close PR if it's going to stable but it's not dev or a hotfix 
    conditions:
      - base=stable      # Merging into stable
      - -head~=(?i)^hotfix # Name of branch does not start with hotfix
      - -head~=^dev$ # Branch is not dev
      - -head~=^mergify
    actions:
      close:
        message: "Please ensure that you are merging any non-hotfix branches
        into `dev`. If this branch is a hotfix, please use the prefix `hotfix` 
        as title to your branch. If you have any questions check out our Tree Hygiene docs
        in the Wiki. Thank you!"
        
  - name: Comment on PR if conflicts are present
    conditions:
      - conflict
    actions:
      comment:
        message: "Thank you for your contribution @{{author}}, however this 
        pull request contains conflicts. Could you please fix them? Feel free
        to contact us on Discord for help. Thank you!"
        
      
  - name: Backport PR to dev if merging to stable
    conditions:
      - base=stable
      - "#approved-reviews-by>=1"
    actions:
      backport:
        branches: ["dev"]

  - name: Merge pull request on approval
    conditions:
      - "#approved-reviews-by>=1"
      - -closed
      - label!=review-required # Only merge PRs that are NOT labeled review-required.
      - check-success=build
    actions:
      merge:
        method: merge
        
  
  - name: Automatically merge copied PRs
    conditions:
      - author~=^mergify\[bot\]$
      - base=dev
      - -conflict
    actions:
      merge:
        method: merge
        
  - name: Delete merged branch
    conditions:
      - merged
    actions:
      delete_head_branch: {}
        
